#!/bin/bash

# --- Configuration ---
# Define the name of the text file containing PDB IDs (one per line)
PDB_ID_LIST_FILE="pdb_ids.txt"

# Define filename patterns/suffixes based on previous steps
GRID_SUFFIX="_gridgen-gridgen.zip"          # Suffix for grid files
LIGAND_SUFFIX="_Ligand.maegz" # Suffix for prepared ligand files
OUTPUT_SUFFIX="_dock_SP"                 # Suffix for the output base name

# Define Glide Docking Parameters (modify as needed)
# Match the force field used for grid generation and ligand prep!
FORCEFIELD="OPLS4"
PRECISION="SP"
POSES_PER_LIG=5
POSTDOCK_NPOSE=15 # Should generally be <= POSES_PER_LIG
WRITE_XP_DESC="no" # Compatible with PRECISION SP
COMPRESS_POSES="TRUE"

# Load Schrödinger environment module (adjust if necessary)
echo "Loading Schrodinger environment..."
ml Schrodinger_Suites
ml # Optional: Display loaded modules

# Check if SCHRODINGER variable is set
if [ -z "$SCHRODINGER" ]; then
  echo "Error: SCHRODINGER environment variable is not set."
  exit 1
fi
echo "Schrodinger base directory: $SCHRODINGER"

# Check if PDB ID list file exists
if [ ! -f "$PDB_ID_LIST_FILE" ]; then
    echo "Error: Input PDB ID list file '$PDB_ID_LIST_FILE' not found."
    exit 1
fi

echo "Starting Batch Glide Docking Jobs from $PDB_ID_LIST_FILE..."
echo "-----------------------------------------------------"

# --- Read PDB ID list and Launch Jobs ---
# Reads the PDB ID file line by line
while IFS= read -r pdb_id || [[ -n "$pdb_id" ]]; do
    # Skip empty lines
    if [ -z "$pdb_id" ]; then
        continue
    fi

    echo "--- Processing PDB ID: $pdb_id ---"

    # --- Construct File Names ---
    GRID_FILE="${pdb_id}${GRID_SUFFIX}"
    LIGAND_FILE="${pdb_id}${LIGAND_SUFFIX}"
    OUTPUT_BASE="${pdb_id}${OUTPUT_SUFFIX}"

    echo "  Grid File:   $GRID_FILE"
    echo "  Ligand File: $LIGAND_FILE"
    echo "  Output Base: $OUTPUT_BASE"

    # --- Define Specific Job File Names ---
    DOCKING_INPUT_FILE="${OUTPUT_BASE}_dock.in"
    JOBNAME="${OUTPUT_BASE}_dock"
    EXPECTED_OUTPUT_PV="${JOBNAME}_pv.maegz"

    # --- Check if input files exist ---
    if [ ! -f "$GRID_FILE" ]; then
        echo "  [SKIP] Error: Grid file '$GRID_FILE' not found."
        echo "-----------------------------------------------------"
        continue
    fi
    if [ ! -f "$LIGAND_FILE" ]; then
        echo "  [SKIP] Error: Ligand file '$LIGAND_FILE' not found."
        echo "-----------------------------------------------------"
        continue
    fi

    # --- Check if output already exists ---
    if [ -f "$EXPECTED_OUTPUT_PV" ]; then
        echo "  [SKIP] Output file '$EXPECTED_OUTPUT_PV' already exists."
        echo "-----------------------------------------------------"
        continue
    fi

    # --- Generate the Glide Docking Input (.in) File ---
    echo "  Generating input file: $DOCKING_INPUT_FILE"
    cat << EOF > "$DOCKING_INPUT_FILE"
# Glide Docking Input File generated by script for $pdb_id
GRIDFILE          $GRID_FILE
LIGANDFILE        $LIGAND_FILE
FORCEFIELD        $FORCEFIELD
PRECISION         $PRECISION
POSES_PER_LIG     $POSES_PER_LIG
POSTDOCK_NPOSE    $POSTDOCK_NPOSE
WRITE_XP_DESC     $WRITE_XP_DESC
COMPRESS_POSES    $COMPRESS_POSES
# OUTPUTDIR         ./ # Optional: uncomment to specify output dir
EOF

    if [ ! -f "$DOCKING_INPUT_FILE" ]; then
        echo "  [FAIL] Error: Failed to create docking input file '$DOCKING_INPUT_FILE'."
        echo "-----------------------------------------------------"
        continue # Skip to next PDB ID
    fi

    # --- Run Glide Docking ---
    echo "  Submitting Glide docking job: $JOBNAME"
    "$SCHRODINGER/glide" "$DOCKING_INPUT_FILE" -WAIT -JOBNAME "$JOBNAME"

    # --- Check Glide Exit Status ---
    EXIT_CODE=$? # Capture exit status immediately
    if [ $EXIT_CODE -eq 0 ] && [ -f "$EXPECTED_OUTPUT_PV" ]; then
        echo "  [SUCCESS] Successfully completed docking job: $JOBNAME"
        # Optional: remove the .in file after successful run
        # rm "$DOCKING_INPUT_FILE"
    else
        echo "  [FAIL] Error: Glide docking job '$JOBNAME' failed with exit code $EXIT_CODE."
        echo "  Check the log file: ${JOBNAME}.log"
        # Optional: remove the potentially incomplete output file
        # rm -f "$EXPECTED_OUTPUT_PV"
        # Decide if you want the script to stop on failure or continue
        # exit $EXIT_CODE # Uncomment to stop on first failure
    fi

    echo "-----------------------------------------------------"

done < "$PDB_ID_LIST_FILE" # Feed the file into the while loop

echo "All docking jobs submitted or checked."
exit 0
